import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ToastProvider } from '@/providers/toast-provider';
import AuthProvider from '@/providers/auth-provider';
import { ModalProvider } from '@/providers/modal-store.provider';
import { PrimeReactProvider, PrimeReactContext } from 'primereact/api';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Nedd Ecommerce',
    description: 'Generated by Nedd',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <PrimeReactProvider>
                    <AuthProvider>
                        <ToastProvider />
                        <ModalProvider />
                        {children}
                    </AuthProvider>
                </PrimeReactProvider>
            </body>
        </html>
    );
}
